export const GET_TOPICS_REQUEST = 'GET_TOPICS_REQUEST';
export const GET_TOPICS_SUCCESS = 'GET_TOPICS_SUCCESS';
export const GET_TOPICS_FAILURE = 'GET_TOPICS_FAILURE';

export const ADD_LINK_REQUEST = 'ADD_LINK_REQUEST';
export const ADD_LINK_SUCCESS = 'ADD_LINK_SUCCESS';
export const ADD_LINK_FAILURE = 'ADD_LINK_FAILURE';

export const GET_LINKS_REQUEST = 'GET_LINKS_REQUEST';
export const GET_LINKS_SUCCESS = 'GET_LINKS_SUCCESS';
export const GET_LINKS_FAILURE = 'GET_LINKS_FAILURE';

export const EDIT_LINK_REQUEST = 'EDIT_LINK_REQUEST';
export const EDIT_LINK_SUCCESS = 'EDIT_LINK_SUCCESS';
export const EDIT_LINK_FAILURE = 'EDIT_LINK_FAILURE';

export const DELETE_LINK_REQUEST = 'DELETE_LINK_REQUEST';
export const DELETE_LINK_SUCCESS = 'DELETE_LINK_SUCCESS';
export const DELETE_LINK_FAILURE = 'DELETE_LINK_FAILURE';
