export const ADD_LINK = 'ADD_LINK';
export const DATA_LOADED = 'DATA_LOADED';
export const SET_TOPICS = 'SET_TOPICS';

export const GET_LINKS_REQUEST = 'GET_LINKS_REQUEST';
export const GET_LINKS_SUCCESS = 'GET_LINKS_SUCCESS';
export const GET_LINKS_FAILURE = 'GET_LINKS_FAILURE';

export const DELETE_LINK_REQUEST = 'DELETE_LINK_REQUEST';
export const DELETE_LINK_SUCCESS = 'DELETE_LINK_SUCCESS';
export const DELETE_LINK_FAILURE = 'DELETE_LINK_FAILURE';

