export const ADD_LINK = 'ADD_LINK';
export const DATA_LOADED = 'DATA_LOADED';
export const SET_TOPICS = 'SET_TOPICS';

export const GET_LINKS_REQUEST = 'GET_LINKS_REQUEST';
export const GET_LINKS_SUCCESS = 'GET_LINKS_SUCCESS';
export const GET_LINKS_FAILURE = 'GET_LINKS_FAILURE';

